max_width = 120
use_small_heuristics = "Max"
merge_derives = true
newline_style = "Unix"
match_block_trailing_comma = true
use_field_init_shorthand = true
format_strings = true
wrap_comments = true
comment_width = 100
normalize_comments = true
format_code_in_doc_comments = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
